### ISSUE TITLE
Does not recognize @Nested class

### ISSUE THREAD

**Issue by OptiPanda** [stacherzakp/test-navigator-plugin#10]
My test classes are nested for each method to handle multiple test cases

The plugin turns yellow saying my test class is empty wich is not because all the tests are nested inside sublasses.

![image](https://github.com/stacherzakp/test-navigator-plugin/assets/6681223/b88977f5-9972-4a38-a763-92cd92063ae8)

**Comment by stacherzakp** [comment]
Thanks @OptiPanda for the report, I think I have fixed it and now the new version of the plugin is waiting for JetBrains approval. It should take up to 2 business days and version 4.2 should be there.

If you like the plugin, please rate it, if possible. I've got a terrible score (for a valid reason), because the plugin didn't perform well at start 😄
